bots = [
        {
            'username': 'ElizaHahns',
            'password': 'AKJHD97434%^%',
            'followed_accounts': [
                '@Jim_Jordan',
                '@michellemalkin',
                '@michaeljohns',
                '@Heritage',
                '@RedState',
                '@townhallcom',
                '@NRO',
                '@theMRC',
                '@DailyCaller',
                '@TuckerCarlson',
                '@JudgeJeanine',
                '@seanhannity',
                '@IngrahamAngle',
                '@FoxNews',
                '@JesseBWatters',
                '@GregGutfeld'
            ],
            'relevant_tags': [
                '#conservative',
                '#trump',
                '#maga',
                '#republican',
                '#donaldtrump',
                '#kag',
                '#makeamericagreatagain',
                '#trumptrain',
                '#keepamericagreat',
                '#americafirst',
                '#draintheswamp',
                '#rightwing',
                '#republicans',
                '#gop',
                '#fakenews',
                '#alllivesmatter',
                '#libtards',
                '#liberalsnowflakes'
            ]
        },
        {
            'username': 'Allison45555547',
            'password': 'A2IHNDjPu23SNEjfy4ts',
            'followed_accounts': [
                '@democracynow',
                '@IlhanMN',
                '@AOC',
                '@thenation',
                '@joshtpm',
                '@DavidCornDC',
                '@maddow',
                '@SenWarren',
                '@JamesFallows',
                '@KevinMKruse',
                '@SenSanders',
                '@slpng_giants',
                '@RBReich',
                '@mmfa',
                '@thinkprogress',
            ],
            'relevant_tags': [
                '#liberal',
                '#blm',
                '#vote',
                '#berniesanders',
                '#voteblue',
                '#blacklivesmatter',
                '#berniesanders',
                '#progressives',
                '#democrats',
                '#bernie',
                '#socialism',
                '#resist',
                '#votebluenomatterwho',
                '#leftists',
                '#democrat',
                '#republicanssuck',
                '#getoutthevote'
            ]
        }
    ]