name: DASDD Bots CI

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_bots:
    name: Build Python Bots
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Building bots
        run: bazel build //bot:all

  test_bots:
    name: Test Python Bots
    needs: build_bots
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Testing bots
        run: bazel test $(bazel query //bot/...) --test_output=all

  build_push_service:
    name: Build Push Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Installing AWS SDK dependencies
        run: sudo apt-get install libcurl4-openssl-dev libssl-dev uuid-dev zlib1g-dev libpulse-dev
      - name: Building bots
        run: bazel build //push-service:all
#  build:
#    name: Build Push Service
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./push-service
#    steps:
#      - uses: actions/checkout@v2
#      - name: Create out of source build directory
#        run: pwd && mkdir build
#      - name: Generate project Makefile buildsystem
#        run: pwd && cd build && cmake ..
#      - name: Building
#        run: pwd && cd build && make
#  test:
#    name: Test Push Service
#    needs:
#      - build
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./push-service
#    steps:
#      - uses: actions/checkout@v2
#      - name: Create out of source build directory
#        run: pwd && mkdir build
#      - name: Generate project Makefile buildsystem
#        run: pwd && cd build && cmake ..
#      - name: Building
#        run: pwd && cd build && make
#      - name: Run unit test executable in bin directory
#        run: pwd && cd bin && ./testlib
