name: DASDD Bots CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build Push Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./push-service
    steps:
      - uses: actions/checkout@v2
      - name: Create out of source build directory
        run: pwd && mkdir build
      - name: Generate project Makefile buildsystem
        run: pwd && cd build && cmake ..
      - name: Building
        run: pwd && cd build && make
  test:
    name: Test Push Service
    needs:
      - build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./push-service
    steps:
      - uses: actions/checkout@v2
      - name: Create out of source build directory
        run: mkdir build && cd build
      - name: Generate project Makefile buildsystem
        run: cmake ..
      - name: Building
        run: make
      - name: Run unit test executable in bin directory
        run: cd ../bin && ./testlib